# Note: All operators are binary operators. For more than two operands, you may use the nested parentheses trick.
# For example:
#    *  A == 1 or (B == 2 and C in [1,2,3])
#    *  (A == 1 and B == 2) or (C not in ["3", "4", 5])

# Common enable rule
.default_enable: &default_enable
  enable:
    - if: IDF_TARGET in ["esp32s3", "esp32p4", "esp32c5"]

# Test apps
test_apps/asio: *default_enable  # asio
test_apps/signals2: *default_enable  # signals2
test_apps/thread: *default_enable  # thread
test_apps/graph: *default_enable  # graph
test_apps/array: *default_enable  # array
test_apps/align: *default_enable  # align
test_apps/format: *default_enable  # format
test_apps/algorithm: *default_enable  # algorithm
test_apps/assign: *default_enable  # assign
test_apps/bimap: *default_enable  # bimap
